### ISSUE TITLE
Port demux

### ISSUE THREAD

**Issue by rcywongaa** [ros-tooling/topic_tools#105]
## Description

Basically porting https://github.com/ros/ros_comm/blob/noetic-devel/tools/topic_tools/src/demux.cpp to ROS2

> demux is a generic ROS topic demultiplexer: one input topic is fanned out to 1 of N output topics. A service is provided to select between the outputs

## Completion Criteria

```
ros2 run topic_tools demux <intopic> <outtopic1> [outtopic2...]
```
- `select` service
- `add` service
- `delete` service
- `list` service

## Implementation Notes / Suggestions

Might be a good first issue since the ROS1 version already exists and this is very similar to Mux which has already been ported to ROS2.

## Testing Notes / Suggestions

It seems the original ROS1 code also didn't have any unit tests for demux

**Comment by christophebedard** [comment]
> Might be a good first issue

I've added the "good first issue" label. PRs are welcome!

**Comment by rcywongaa** [comment]
WIP: https://github.com/ros-tooling/topic_tools/pull/106
