### ISSUE TITLE
Fix Jazzy release to refer to the Jazzy branch for topic_tools repo

### ISSUE THREAD

**Issue by MichaelOrlov** [ros-tooling/topic_tools#108]
## Description
We forgot to create a separate `jazzy` branch for the `topic_tools` repo and released it to Jazzy from the rolling branch.

Need to fix the Jazzy release to refer to the appropriate `jazzy`  branch

## Related Issues
- #107 

## Completion Criteria
* [x] Create jazzy branch from rolling in this repo, and add protection here: https://github.com/ros-tooling/topic_tools/settings/branches
* [x] Change version: rolling in the rosdistro jazzy/distribution.yaml entry for topic_tools to version: jazzy: https://github.com/ros/rosdistro/blob/258800ad9291feb269da3fcbbe8764b98fc94a6b/jazzy/distribution.yaml#L7595-L7612
* [x] Change devel_branch for Jazzy from rolling to jazzy in the release repo: https://github.com/ros2-gbp/topic_tools-release/blob/d3ec3544366ec4e953ca4d5c899e70b4ed5919d9/tracks.yaml#L95

At this point, Rolling and Jazzy will still have the same version of topic_tools, which is fine.

* [x] Create a new release for Rolling on rolling, bumping the major version
* [x] Create a new release for Jazzy on jazzy, bumping the minor version

**Comment by MichaelOrlov** [comment]
@christophebedard I think that creating a new release for Rolling on rolling and bumping the major version without any changes to it doesn't make sense and has no value.

I thought that it make sense to merge #106 on rolling first then bump the major version and do release on rolling.
The same could be done for `Jazzy` - backport #106 to Jazzy branch and then bump minor version on jazzy release and do a release for jazzy.

@clalancette @marcoag - any concern about this ^^^?

**Comment by christophebedard** [comment]
Yeah that's fine. The current version is 1.3.0, so Rolling would then have 1.4.0 and Jazzy would have 1.3.1.

**Comment by clalancette** [comment]
> @christophebedard I think that creating a new release for Rolling on rolling and bumping the major version without any changes to it doesn't make sense and has no value.

We do this for all of the core ROS 2 repositories (though we bump the minor version, not the major).  That is, if the version of a Jazzy package is X.Y.Z, we make sure that Rolling is at least X.Y+1.Z.  And thereafter, we only ever bump the patch version for Jazzy.  It isn't ideal, as we can't really encode semver that way, but it ensures that we never "interleave" version numbers between Rolling and released distributions.  It also ensures that we can always release, even if there doesn't happen to be PRs that we want merge in.

For this package, you can do it however you want.  If you just want to get the version numbers straight now, you can bump it without any changes.  If you'd rather get #106 in first, then merge that, bump the major (or minor), and backport to Jazzy, which will only bump the minor (or patch).
