### ISSUE TITLE
transform node is not available anymore for ros2

### ISSUE THREAD

**Issue by gdamion** [ros-tooling/topic_tools#114]
## Description

Since v1.3.1 of the package, the node `transform` is not avaliable anymore:

```
Caught exception in launch (see debug for traceback): executable 'transform' not found on the libexec directory '/opt/ros/jazzy/lib/topic_tools' 
```

### Expected Behavior

The python file `transform.py` should be properly installed by the builder

### Actual Behavior
The `transform.py` seems to be not installed to the package by the builder

## To Reproduce

Run with version v1.3.1: 

```
ros2 run topic_tools transform
```

## System (please complete the following information)

 - OS: Ubuntu 24.04
 - ROS 2 Distro: Jazzy

**Comment by christophebedard** [comment]
Did it ever work?

**Comment by christophebedard** [comment]
Ah, nevermind, I see that #106/#109 broke it and that someone created #115 to fix it.

**Comment by acristoffers** [comment]
How long until the changes in #115 hit the APT repo? I'm trying to upgrade a project to Jazzy but this bug is blocking it :(

**Comment by christophebedard** [comment]
Unfortunately, #115 hasn't been backported to Jazzy. I'll do it now. After that, I'll need to create a new release, and then we'll have to wait for the next Jazzy sync for it to be available from the apt repository, which might take multiple weeks.

**Comment by christophebedard** [comment]
Alright, I've backported everything to Jazzy and created a new release: 1.3.2. rosdistro PR: https://github.com/ros/rosdistro/pull/43182. Once this PR gets merged, we'll have to wait for the next Jazzy sync. Once that happens, I'll close this issue.

**Comment by christophebedard** [comment]
https://github.com/ros/rosdistro/pull/43182 was merged, so I'll close this. I would expect the next Jazzy sync to either happen this week (since ROSCon is next week and people will be busy) or in early November.
