### ISSUE TITLE
Foxy Implementation

### ISSUE THREAD

**Issue by OsamaThakur** [ros-tooling/topic_tools#50]
Hello, 

Just curious how to use this with ros2 foxy, I run into issues when cloning the repo and building from source.

best regards

**Comment by MichaelOrlov** [comment]
@OsamaThakur This package was backported after Foxy release.  
Therefore no guarantee that it will be compiled with Foxy branch.  
@emersonknapp please correct me if I am wrong.

**Comment by emersonknapp** [comment]
> This package was backported after Foxy release.

This package was _originally written_ after Foxy release.  There is no expectation that it would be able to compile on Foxy. If you would like to create a Foxy-compatible branch and submit that to this repo, there would be no problem with that. However, Foxy's end-of-life is in about 100 days from now, so it may not be worth the effort

**Comment by OsamaThakur** [comment]
@MichaelOrlov @emersonknapp Thank you guys for your feedback, I will take them into consideration
