### ISSUE TITLE
Branch Humble and Iron release branches, make sure they build

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/topic_tools#62]
Right now this package was released into Humble and Iron pointing to the `main` branch - there's no guarantee this code will continue to build in those distros if we keep building against Rolling.

We should create dedicated release branches for those distros and fix them if necessary to build in those environments, then update rosdistro with a new patch release pointing to the proper branches.

**Comment by emersonknapp** [comment]
We need to consider version numbering for distros. I'm inclined to give a new major version number to each distro, to allow for minor version bumps within backports. So Humble could stay on v1.x, Iron on v2.x, and bump Rolling to 3.x, which it will give to Jazzy when that comes out.

On every distro release, the process would look like
1. Make a final release for new distro
2. Cut a branch for the distro - the top commit is the release that was just made
3. Immediately bump major version on Rolling branch

Semantically - this isn't necessarily an API break like major version normally implies, but it would make for easy messaging about what distro a release is from, and let intra-distro updates do minor bumps without any tricky business.

**Comment by emersonknapp** [comment]
The alternative strategy is to do a "monobranch" approach, and use `#ifdef`s or equivalent for features that won't work in a specific distro. At first this is OK but after a while it can get really out of hand, requiring a lot of bookkeeping - so I personally don't think it's the best approach.

**Comment by christophebedard** [comment]
Yeah, I don't like the monobranch approach either. The proposed approach seems fine.

**Comment by MichaelOrlov** [comment]
@emersonknapp Thank you for handling this issue. I agree with your release versioning process and branching proposal.

**Comment by MichaelOrlov** [comment]
TODO: 
1. create branches for Humble, Iron.
2. Create Rolling branch and then switch default branch to the new Rolling.
3. Update release repo. 
   - Clone https://github.com/ros2-gbp/topic_tools-release/blob/94916a90b845d555d579286f2794ea9270e93f20/tracks.yaml#L43C23-L43C23 and change `devel_branch: ` to point  to the newly created branches.
5. Mofdify ROS distro For instance for Humble https://github.com/ros/rosdistro/blob/5602bb7d5ca4069bb4fa5c27e948a67e2da73feb/humble/distribution.yaml#L8028-L8045
6.

**Comment by MichaelOrlov** [comment]
Ok. I've created the `rolling` branch which is pointing to the same hash as main branch currently.
@emersonknapp @clalancette Could you please now switch default branch from main to the rolling in the github settings for this repo.  
Or even better to grant me and @christophebedard github permissions to be able to do that by ourself. We found out that we don't have `admin` permission for this repo.

**Comment by clalancette** [comment]
> Or even better to grant me and @christophebedard github permissions to be able to do that by ourself. We found out that we don't have `admin` permission for this repo.

I've just updated the "approvers" team to have Admin access now (it was only "Maintain" before).  That should include all 3 people involved in this issue.

**Comment by MichaelOrlov** [comment]
@clalancette Thanks. Now I have access to the repo settings. However still can't figure out what need to do in settings to switch the default branch to the rolling. i.e. remap main to the rolling.

**Comment by clalancette** [comment]
> @clalancette Thanks. Now I have access to the repo settings. However still can't figure out what need to do in settings to switch the default branch to the rolling. i.e. remap main to the rolling.

It looks like it has already been done.  But for the future, it is in Settings->General->Default Branch

**Comment by MichaelOrlov** [comment]
@clalancette Thanks. noted. Curious about branch protection rules. Currently, we have a protection rule for the main branch only. Should we make a new protection rule for the rolling branch as well?

**Comment by clalancette** [comment]
> @clalancette Thanks. noted. Curious about branch protection rules. Currently, we have a protection rule for the main branch only. Should we make a new protection rule for the rolling branch as well?

That's up to you on how you want to manage the repository.  Some of the current protection settings wouldn't work for the core repositories, but for a third-party repository like this you can manage it how you like.

**Comment by MichaelOrlov** [comment]
I've created protection rules for newly created branches `rolling`, `humble`, `iron`. 
However, can't setup to apply `DCO` check in the `Require status checks to pass before merging` item. 
It seems that DCO rule is not available for those branches.
![image](https://github.com/ros-tooling/topic_tools/assets/7294722/70739e80-c369-495a-b298-1a2fd2e01343)
Although it is available for the main branch
![image](https://github.com/ros-tooling/topic_tools/assets/7294722/91039f91-ac7d-40da-aa8c-2923fa629525)

@clalancette @christophebedard Do you know if there is some magic behind the scene?

**Comment by christophebedard** [comment]
> Do you know if there is some magic behind the scene?

I was able to add DCO to all new branches.

**Comment by MichaelOrlov** [comment]
@christophebedard Wouldn't you mind to tackle action items 3 and 4 from the our plan?

- [ ] 3. Update release repo. 
   - Clone https://github.com/ros2-gbp/topic_tools-release/blob/94916a90b845d555d579286f2794ea9270e93f20/tracks.yaml#L43C23-L43C23 and change `devel_branch: ` to point  to the newly created branches.
- [ ] 4. Mofdify ROS distro For instance for Humble https://github.com/ros/rosdistro/blob/5602bb7d5ca4069bb4fa5c27e948a67e2da73feb/humble/distribution.yaml#L8028-L8045

**Comment by christophebedard** [comment]
Sure, I'll do it now.

**Comment by MichaelOrlov** [comment]
Thanks! :handshake:

**Comment by christophebedard** [comment]
All done:

3. Release repo updated: https://github.com/ros2-gbp/topic_tools-release/commit/6ae603ac0b5ecd039e99839aceae646da3ddfa5a
4. rosdistro PR: https://github.com/ros/rosdistro/pull/39021

**Comment by MichaelOrlov** [comment]
Ok. As soon as https://github.com/ros/rosdistro/pull/39021 will be merged we can spawn new labels with increased minor versions for each distro branch and make a bloom releases.

**Comment by christophebedard** [comment]
> As soon as https://github.com/ros/rosdistro/pull/39021 will be merged we can spawn new labels with increased minor versions for each distro branch and make a bloom releases.

The rosdistro PR has been merged. Let's wait until next week to do the new releases, since I think the buildfarm is going to be offline for the thanksgiving weekend anyway.

**Comment by christophebedard** [comment]
Distro branches exist, and new releases have been made (https://github.com/ros-tooling/topic_tools/issues/83#issuecomment-1830440530), so I'm closing this.
